// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ListaEspera.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261010165117_AtualizandoTablesAdicionandoClassGroups")]
    partial class AtualizandoTablesAdicionandoClassGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ListaEspera.Models.AttendantModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Attendants");
                });

            modelBuilder.Entity("ListaEspera.Models.ClassGroupModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassTimeTable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Days")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("int");

                    b.Property<int>("MinAge")
                        .HasColumnType("int");

                    b.Property<int>("ModalityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModalityId");

                    b.ToTable("ClassGroups");
                });

            modelBuilder.Entity("ListaEspera.Models.ClientModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ListaEspera.Models.ModalityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Modalitys");
                });

            modelBuilder.Entity("ListaEspera.Models.WaitListModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendantId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassGroupModelId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ContactDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Credential")
                        .HasColumnType("int");

                    b.Property<int>("ModalityId")
                        .HasColumnType("int");

                    b.Property<int>("PositionStats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttendantId");

                    b.HasIndex("ClassGroupModelId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ModalityId");

                    b.ToTable("WaitLists");
                });

            modelBuilder.Entity("ListaEspera.Models.ClassGroupModel", b =>
                {
                    b.HasOne("ListaEspera.Models.ModalityModel", "Modality")
                        .WithMany("ClassGroup")
                        .HasForeignKey("ModalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modality");
                });

            modelBuilder.Entity("ListaEspera.Models.WaitListModel", b =>
                {
                    b.HasOne("ListaEspera.Models.AttendantModel", "Attendant")
                        .WithMany("ListaEspera")
                        .HasForeignKey("AttendantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ListaEspera.Models.ClassGroupModel", null)
                        .WithMany("ListaEspera")
                        .HasForeignKey("ClassGroupModelId");

                    b.HasOne("ListaEspera.Models.ClientModel", "Client")
                        .WithMany("ListaEspera")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ListaEspera.Models.ModalityModel", "Modality")
                        .WithMany()
                        .HasForeignKey("ModalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendant");

                    b.Navigation("Client");

                    b.Navigation("Modality");
                });

            modelBuilder.Entity("ListaEspera.Models.AttendantModel", b =>
                {
                    b.Navigation("ListaEspera");
                });

            modelBuilder.Entity("ListaEspera.Models.ClassGroupModel", b =>
                {
                    b.Navigation("ListaEspera");
                });

            modelBuilder.Entity("ListaEspera.Models.ClientModel", b =>
                {
                    b.Navigation("ListaEspera");
                });

            modelBuilder.Entity("ListaEspera.Models.ModalityModel", b =>
                {
                    b.Navigation("ClassGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
